<?php
use Magento\Framework\Escaper;

/**
 * @var $block \Deuna\Checkout\Block\Checkout
 * @var Escaper $escaper
 */

$env = $block->getEnv();
$apiKey = $block->getApiKey();
$btnLabel = $escaper->escapeHtml(__('Proceed to Checkout'));
?>

<div id="deuna-checkout" data-bind="scope:'duna'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#duna-checkout": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "deuna": {
                        "component": "Dena_Checkout/js/checkout-widget",
                        "env": "<?= $env ?>",
                        "apiKey": "<?= $apiKey ?>",
                        "btnLabel": "<?= $btnLabel ?>"
                    }
                }
            }
        }
    }
    </script>
</div>
